[package]
name = "maze-wars-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
local-ip-address = "0.5.7"

[dependencies.uuid]
version = "1.7.0"
features = [
    "v4", 
    "serde"               # Lets you generate random UUIDs
]